@apiKey = {{$dotenv REACT_APP_SUPABASE_ANON_KEY}}

@hostname = {{$dotenv REACT_APP_SUPABASE_URL}}

@contentType = application/json

@host = {{hostname}}/rest/v1/


### Obtener TODOS los Socios
GET {{host}}socios 
apikey:{{apiKey}}
Content-Type: {{contentType}}


### agregar Socios
POST {{host}}socios 
apikey:{{apiKey}}
Content-Type: {{contentType}}

{"nombre":"Delete Socio2","telefono":"99999999999"}

### Editar Socios
PATCH {{host}}socios?id=eq.5
apikey:{{apiKey}}
Content-Type: {{contentType}}

{"nombre":"Luis Gonzalez", "email":"luis@gmail.com"}

### Obtener TODOS los Socios y pagos ???
GET {{host}}socios?deleted=eq.false&select=*,pagos(monto,nota)
apikey:{{apiKey}}
Content-Type: {{contentType}}

### Eliminar Pago de  Socios
DELETE {{host}}pagos?id=eq.44
apikey:{{apiKey}}
Content-Type: {{contentType}}

### Editar Socios
PATCH {{host}}socios?id=eq.35
apikey:{{apiKey}}
Content-Type: {{contentType}}

