# Rol Moderador
# @token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MTFjODRiZWRiMTVmODIzZjQ5NWFmZmMiLCJleHAiOjE2MzgzMTY5NjI5ODgsImlhdCI6MTYzNzQ1Mjk2Mjk4OCwidXNlcm5hbWUiOiJtb2RlcmF0b3J0ZXN0IiwiaWQiOiI2MTFjODRiZWRiMTVmODIzZjQ5NWFmZmMifQ.A-08p65oPTiVReMcElkxM8M2Y1xPmnz0tBsqao1oZxo
# Rol Admin
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MDk1NzlmZTMxNmE4ODFjMDRjYjg4ZTQiLCJleHAiOjE2NDQ2OTk2NzcwMjQsImlhdCI6MTY0MzgzNTY3NzAyNSwidXNlcm5hbWUiOiJmb203OCIsImlkIjoiNjA5NTc5ZmUzMTZhODgxYzA0Y2I4OGU0In0.ILNjW1OcfM5LQGfYItRpbcNVMPXmkxEJZ235Rm3xVnc

@hostnameHeroku = profut.herokuapp.com
@hostnameLocal = localhost

@port = 4000
@hostLocal = {{hostnameLocal}}:{{port}}
@hostHeroku = {{hostnameHeroku}}

@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

@host = {{hostLocal}}/api

### Agregar Evento de Monedas
POST https://vemmgkfadvuhcdezrdax.supabase.co/rest/v1/cursos 
apikey:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlbW1na2ZhZHZ1aGNkZXpyZGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDg0MzYyNDIsImV4cCI6MTk2NDAxMjI0Mn0.uQMnOyDD8NXyOrP2-ulFS8qep_v2a7AbA2SxYMiLt9E
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjQ4NDQxMzgyLCJzdWIiOiIxNmQxMGY1ZS02NGQxLTQyMTctYWNlZS1hZTk4OGYxODVmZjkiLCJlbWFpbCI6ImZvbTc4YUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQifQ.rAIH2oDuroNA0WSHtYoaKHimB7NMcmdoS7kaWPc1jEg
Content-Type: application/json 

[{"nombre":"2 C"},{"nombre":"2 D"},{"nombre":"3 A"},{"nombre":"3 B"},{"nombre":"3 C"},{"nombre":"3 D"},{"nombre":"4 A"},{"nombre":"4 B"},{"nombre":"4 C"},{"nombre":"4 D"},{"nombre":"5 A"},{"nombre":"5 B"},{"nombre":"5 C"},{"nombre":"5 D"},{"nombre":"6 A"},{"nombre":"6 B"},{"nombre":"6 C"},{"nombre":"6 D"}]

### Agregar Evento de Monedas
POST https://vemmgkfadvuhcdezrdax.supabase.co/rest/v1/socios 
apikey:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlbW1na2ZhZHZ1aGNkZXpyZGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDg0MzYyNDIsImV4cCI6MTk2NDAxMjI0Mn0.uQMnOyDD8NXyOrP2-ulFS8qep_v2a7AbA2SxYMiLt9E
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjQ4NDQ3NDEwLCJzdWIiOiIxNmQxMGY1ZS02NGQxLTQyMTctYWNlZS1hZTk4OGYxODVmZjkiLCJlbWFpbCI6ImZvbTc4YUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQifQ.xunSzY4R1RpqscEszvtqQ-3UpgUeSE-dkqEbkRWzl_0
Content-Type: application/json 

[
    {"nombre":"LESCANO ALDANA","telefono":"3489440989"},
    {"nombre":"MONTIEL SERGIO","telefono":"3489236343"},
    {"nombre":"NUÑEZ GISELLA","telefono":"3489569107"},
    {"nombre":"CASTRO MIRIAN","telefono":"3489657165"},
    {"nombre":"PELLIGRINI ZAMIRA","telefono":"3489685520"},
    {"nombre":"CIVICO PATRICIA ","telefono":"3489661581"},
    {"nombre":"CIANCHETTA MATIAS","telefono":"1123900106"},
    {"nombre":"LEVIN FABIAN","telefono":"3489594360"},
    {"nombre":"PARELSTEIN JESICA","telefono":"3489442609"},
    {"nombre":"BONELLI JOHANA","telefono":"3489684891"},
    {"nombre":"ROMINA VILLALBA","telefono":"3489599653"},
    {"nombre":"LUNA PAOLA","telefono":"3489439219"},
    {"nombre":"VILLACOTA MIRIAM","telefono":"3489439219"}
]

### Agregar Evento de Monedas
GET https://vemmgkfadvuhcdezrdax.supabase.co/rest/v1/socios 
apikey:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlbW1na2ZhZHZ1aGNkZXpyZGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDg0MzYyNDIsImV4cCI6MTk2NDAxMjI0Mn0.uQMnOyDD8NXyOrP2-ulFS8qep_v2a7AbA2SxYMiLt9E
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjQ4NDQ3NDEwLCJzdWIiOiIxNmQxMGY1ZS02NGQxLTQyMTctYWNlZS1hZTk4OGYxODVmZjkiLCJlbWFpbCI6ImZvbTc4YUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQifQ.xunSzY4R1RpqscEszvtqQ-3UpgUeSE-dkqEbkRWzl_0

### Agregar Evento de Monedas
GET https://vemmgkfadvuhcdezrdax.supabase.co/rest/v1/socios?nombre=eq.SACK ANABELA&select=* 
apikey:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlbW1na2ZhZHZ1aGNkZXpyZGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDg0MzYyNDIsImV4cCI6MTk2NDAxMjI0Mn0.uQMnOyDD8NXyOrP2-ulFS8qep_v2a7AbA2SxYMiLt9E
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjQ4NTA4MjkzLCJzdWIiOiIxNmQxMGY1ZS02NGQxLTQyMTctYWNlZS1hZTk4OGYxODVmZjkiLCJlbWFpbCI6ImZvbTc4YUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQifQ.TO48l_tCfpbuIJujXCaOW3NSsnm860f6-Wv-4TwOFVk